executor-machine: &executor-machine

jobs:
    test_front_catalogs_ce:
        machine:
            image: *executor-machine
            docker_layer_caching: true
        steps:
            -   attach_workspace:
                    at: ~/
            -   fix_files_permissions
            -   load_docker_image_node
            -   run:
                    name: Lint front
                    command: make catalogs-lint-front
            -   run:
                    name: Unit front
                    command: make catalogs-unit-front
            -   run:
                    name: Integration front
                    command: make catalogs-integration-front
